### ISSUE TITLE
Error creating file in MSF 4.10

### ISSUE THREAD

**Issue by crazybrker** [g0tmi1k/mpc#1]
The generated cmd for msfvenom in lines 360-558 use "-o outputfile" which is not supported with msf 4.10. A quick change to "> outputfile" will fix the issue.

Cheers. I put 1 beer on your tab...

**Comment by g0tmi1k** [comment]
Good point! Thanks for the heads up.
Will have this fixed in v1.3 =).
^ Will try to get it released _soon_ (week **ish**).

**Comment by g0tmi1k** [comment]
All fixed up in v1.3 =).

Commit: 007db2720fbddd9b34dbfdfc91aa52a6d5c9b432
Release: https://github.com/g0tmi1k/mpc/releases/tag/v1.3
