### ISSUE TITLE
BUG: unable to find IP 

### ISSUE THREAD

**Issue by royharoush** [g0tmi1k/mpc#3]
Hi,
I've just setup the rolling repo and upgraded and it looks like the new ifconfig version is preventing MPC from identifying the IP on the interfaces. 

 `root@kaliiso:/var/github/royharoush/mpc# ./mpc.sh 
 [*] Msfvenom Payload Creator (MPC v1.4)
 [i] Something went wrong. Couldn't discover IP addresses. =(
 [i] Need to manually define it.   ./mpc.sh --ip <IP>
`
even when defining an IP manually it won't work.

`root@kaliiso:/var/github/royharoush/mpc# ./mpc.sh --ip 10.10.10.10
 [*] Msfvenom Payload Creator (MPC v1.4)
 [i] Something went wrong. Couldn't discover IP addresses. =(
 [i] Need to manually define it.   ./mpc.sh --ip <IP>`

the new ifconfig output is shown in this format: 
![image](https://cloud.githubusercontent.com/assets/8113056/12645399/7dc19bdc-c5d2-11e5-9675-52b18be46c3c.png)

the old one: 

![image](https://cloud.githubusercontent.com/assets/8113056/12645391/7546f380-c5d2-11e5-8f21-09a8f4b89a4b.png)

obviously this isn't really an issue since we can only keep using the old repo, at least for a while. 
just thought you should know. 

Roy

**Comment by g0tmi1k** [comment]
Thanks for the heads up. Will dig into it tomorrow!

**Comment by g0tmi1k** [comment]
Fixed!
Thanks for the report @royharoush =)
