### ISSUE TITLE
exe-service windows format

### ISSUE THREAD

**Issue by kernelsmith** [g0tmi1k/mpc#7]
AFAICT, there's no way to have mpc build a service exe (vs a standard exe).  The msfvenom command would be `msfvenom -p blah -f exe-service`

I made the changes to accommodate it, testing now, want a PR?

**Comment by kernelsmith** [comment]
seems to be working just fine

**Comment by g0tmi1k** [comment]
Feel free to open a PR so it can be added!

**Comment by kernelsmith** [comment]
holy cow I'd forgotten about this.  Let me see if I can still find it

**Comment by kernelsmith** [comment]
found it.  Rebased it to the current master branch.  Encountered a file naming bug, fixed that, doing final testing

**Comment by g0tmi1k** [comment]
#8 fixes this.
Closing
