### ISSUE TITLE
Add option to specify custom IP/hostname for payload

### ISSUE THREAD

**Issue by Cave-Johnson** [g0tmi1k/mpc#9]
Thanks for your hard work on this script!
Would it be possible to add an option to specify a different IP or a domain when selecting ip address (eth interface) use? Some complex setups mean we use diff IP addresses to those of the interfaces

Also will 64bit payloads be supported?

**Comment by g0tmi1k** [comment]
Nice ideas

Could be do-able (both)

If I get the time, will try and do it  - else PRs are accepted!
